version: '3.8'

services:
  # حاوية قاعدة البيانات
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong@Pass123
    ports:
      - "1433:1433"

  # حاوية التخزين المؤقت
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  # حاوية مشروعك
  ecommerce-api:
    build:
      context: .
      dockerfile: ECommerceApi/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      # لاحظ: الدوكر بيقرا المتغيرات دي وبيبدلها باللي في appsettings.json
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=ECommerceApiDb;User Id=sa;Password=YourStrong@Pass123;TrustServerCertificate=True;
      - ConnectionStrings__Redis=redis:6379
    depends_on:
      - sqlserver
      - redis